### PR TITLE
Feat alert component

### PR DESCRIPTION
**Pull request by prathmeshjagtap**
Added 3 types of alert components 
1)Simple  Alert
2)Outline Alert
3) Icon Alert
Animation_alert

### CODE REVIEW

**Comment by SanjayJatti** [comment]
Looking amazing Prathmesh! You can add hamburger icon for small screen later. You can merge it.

**Comment by amarphule** [comment]
Very nice Prathamesh, You have done a fantastic job. 
One suggestion If Alert components had close(X) action that would be great.

**Comment by prathmeshjagtap** [comment]
> Very nice Prathamesh, You have done a fantastic job. One suggestion If Alert components had close(X) action that would be great.

yes for now I have only added HTML CSS I think close option will require js which I will add later

**Comment by prathmeshjagtap** [comment]
> Looking amazing Prathmesh! You can add a hamburger icon for a small screen later. You can merge it.

yes I will work on hamburger Icon

**Pull request merged**
